default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: aman
  host: localhost

development:
  <<: *default
  database: social_media_scheduler_development

test:
  <<: *default
  database: social_media_scheduler_test

production:
  <<: *default
  database: social_media_scheduler_production
  username: postgres
  password: aman
